name: Backend - CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # Altere conforme necessário

      - name: Restore dependencies
        run: dotnet restore ./backend/Backend.sln

      - name: Build
        run: dotnet build ./backend/Backend.sln --configuration Release --no-restore
