name: Backend - CI

on:
  push:
    branches: [ "master" ]
    paths:
      - 'backend/**'  

  pull_request:
    branches: [ "master" ]
    paths:
      - 'backend/**' 

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./backend/Backend.sln

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish
        working-directory: backend

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-publish
          path: backend/publish
