name: Backend - CD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Login no Railway
      run: npm install -g @railway/cli

    - name: Deploy para Railway com Docker Compose
      working-directory: backend
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: railway up --service "backend"
