name: Backend - CD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Instalar Railway CLI
      run: npm install -g @railway/cli

    - name: Linkar com projeto Railway (caso necessário)
      working-directory: backend
      env:
        RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: railway link --project 98383233-cba5-4d58-a819-f2cead584136

    - name: Deploy API para Railway com Docker Compose
      working-directory: backend
      env:
        RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: railway up --service backend
