name: Backend - CD

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      ConnectionStrings__Database: ${{ secrets.SQL_CONNECTION_STRING }} 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: backend

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: backend

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish
        working-directory: backend

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: coreapps-testedeploy-api
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
          
