name: Backend - CD

on:
  # push:
  #   branches:
  #     - master
  workflow_run:
    workflows: ["Backend - CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment:
      name: cd-approval  # Requer aprovação manual

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-publish-${{ github.ref_name }}
          path: ./publish
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: coreapps-testedeploy-api
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
          
